version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestao_tarefas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db/gestao_tarefas
      FLASK_APP: /app/api/app.py
      PORT: 5000
      # SECRET_KEY
    ports:
      - "5000:5000"
    depends_on:
      - db

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    environment:
      API_URL: http://web:5000/tarefas
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db/gestao_tarefas
    depends_on:
      - web
    stdin_open: true
    tty: true

  tests:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db/gestao_tarefas
    command: ["pytest", "/app/tests/unit"]
    depends_on:
      - db
      - web
volumes:
  db_data: