version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestao_tarefas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: ${FLASK_ENV}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      FLASK_APP: ${FLASK_APP}
      HOST: ${HOST}
      PORT: ${PORT}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
      API_KEY: ${API_KEY}
    ports:
      - "443:5000"
    depends_on:
      - db
    volumes:
      - ./api/ssl/server.crt:/app/api/ssl/server.crt
      - ./api/ssl/server.key:/app/api/ssl/server.key

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
    environment:
      API_URL: https://web:5000/tarefas
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db/gestao_tarefas
      CERT_PATH: /cli/ssl/server.crt
      API_KEY: ${API_KEY}
    depends_on:
      - web
    volumes:
    - ./api/ssl/server.crt:/cli/ssl/server.crt

  tests:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db/gestao_tarefas
    command: ["pytest", "/app/tests/unit"]
    depends_on:
      - db
      - web
volumes:
  db_data: